### PR TITLE
Asset - Endpoint for pushing consumptions

### PR DESCRIPTION
**Pull request by OliveGerste**
Unit Tests will be added in a separate PR.

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@Ninjeneer Could you please check this PR (only the routes and OAS file)
Thanks!

**Comment by Ninjeneer** [comment]
> @Ninjeneer Could you please check this PR (only the routes and OAS file)
> Thanks!

The API part looks good to me!

**Comment by LucasBrazi06** [comment]
@OliveGerste latest merges generated conflicts, could you check? Thanks.

**Comment by OliveGerste** [comment]
I resolved the conflicts, but was not able to test again yet (DB backup is making some trouble).

Anyway it should work as before as the changes were not big or complicated.

**Pull request merged**
