### PR TITLE
Change tenant id to object tag storage

### PR DESCRIPTION
**Pull request by RohanAntony**

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@RohanAntony  FYI, your PR is in Draft and in To Be Reviewed pipeline

**Comment by RohanAntony** [comment]
> @RohanAntony FYI, your PR is in Draft and in To Be Reviewed pipeline

I just select the reviewers and create draft pull request. I think it automatically adds it in to be reviewed pipeline.

**Comment by RohanAntony** [comment]
@LucasBrazi06 What happened to [ev-sap-pricing-convergent-charging](https://github.com/sap-labs-france/ev-sap-pricing-convergent-charging) repo ? I am getting a 404 error.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 What happened to [ev-sap-pricing-convergent-charging](https://github.com/sap-labs-france/ev-sap-pricing-convergent-charging) repo ? I am getting a 404 error.

Try again?

**Pull request merged**
