### PR TITLE
RFC: Renable retry on axios and disable it on ut.

### PR DESCRIPTION
**Pull request by jerome-benoit**
We can disable it for on other call site if needed.

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
As I wrote, I don't want to enable the retry.

**Comment by jerome-benoit** [comment]
That was meant to be merged after the test, and the ut part is valid and ensure that retry is left disabled in them whatever is put in the config.json file as axios configuration.

In short, you've closed a PR with code in it that actually fix the ut behaviour in all case.

**Comment by LucasBrazi06** [comment]
I wanted this behavior in the whole project

**Comment by jerome-benoit** [comment]
The behaviour can be overridden by the configuration, the ut use axios to mimic the dashboard or mobile clients that never retry. In order to ensure the ut always behave like the clients, that code is necessary. Otherwise the ut behaviour can be not consistent with the clients one. like @ClaudeROSSI remarked, which is not is expected in ut.

**Comment by LucasBrazi06** [comment]
I want this behavior in the usage everywhere in the projet and feature that needs retry will provide explicitly the conf.

**Comment by jerome-benoit** [comment]
The ut never need to retry, letting the code allows them to eventually retry is a bug.

**Comment by LucasBrazi06** [comment]
Today with the default Axios config, by default, there is not retry included unit tests if I'm not mistaken.

**Comment by jerome-benoit** [comment]
> Today with the default Axios config, by default, there is not retry included unit tests if I'm not mistaken.

Sure but the code still permits them to be enabled, which will lead to the previous misbehaviour reported by @ClaudeROSSI. With the other PR, it just can't happen anymore, whatever is changed in the configuration file and the ut behave then consistently like the clients do. That was the only purpose of the other PR.

**Comment by LucasBrazi06** [comment]
> Sure but the code still permits it to be enabled, which will lead to the previous misbehaviour reported by @ClaudeROSSI. With the other PR, it just can't happen anymore, whatever is changed in the configuration file and the ut behave then consistently like the clients do. That was the only purpose of the other PR.

I decided to extend this behavior to the whole backend, so it should be okay by now I think.

**Comment by jerome-benoit** [comment]
I think I will split put the axios ut configuration in the ut configuration file and do an other PR ;) That will be easier than trying to explain that reusing the global configuration for ut is not the correct.

**Comment by LucasBrazi06** [comment]
lol
The global conf should not retry either so it should be consistent I think with the UT.
Indeed, we can have a talk when I'll be on site, no problem :-)

**Comment by jerome-benoit** [comment]
I'll do the PR, you will understand. For the WSClient, we already do the same: ut have it's own configuration to set it up, so ut can behave the way the want independently of the ev-server configuration, default behaviour.

**Pull request closed without merging**
