### PR TITLE
Sub site area - follow up

### PR DESCRIPTION
**Pull request by ClaudeROSSI**

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI Change of Site has been handled in sub-site area, you can check it and give me feedback.
Remaining tasks so far:
- Change of Smart Charging, Voltage, Nbr of Phases -> Propose to change the fill hierarchy
- Change of Power, check children's won't go over the parent's power
@OliveGerste Fyi, we recreated the branch for this topic. You can also check the feature if you want.
Thanks to both of you!

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI, as agreed I just made the following changes:
- Put Site selection before the sub-Site Area
- Assign Site when sub-Site Area is selected first
- Display sub-Site Area in read-only mode for Basic user

Could you double check and let me know so I can move ahead with the next changes:
- Change of Smart Charging, Voltage, Nbr of Phases -> Propose to change the fill hierarchy
- Change of Power, check children's won't go over the parent's power

**Comment by ClaudeROSSI** [comment]
> @ClaudeROSSI I just added the update of transactions, charging stations, assets Org IDs when the Site of a Site Areas (or sub Site Area) has been changed (case 1). Let me know if you find something else, I will implement the Smart Charging flag update in the tree. Thanks!

tested. c'est bon pour moi - sauf les tests qui echouent sur les nouveau code d'erreurs. Nornmal je pense!

**Comment by LucasBrazi06** [comment]
> tested. c'est bon pour moi - sauf les tests qui echouent sur les nouveau code d'erreurs. Nornmal je pense!

Oui, je vais regarder.
Merci !!!

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI 
Unit Tests fixed.
i18n fixed.
Added the update of the Smart Charging in the whole Site Area tree.
Let me know.
I'll do the latest one 'Check of power limits in children'

**Comment by OliveGerste** [comment]
@LucasBrazi06  Thanks for all the refinements. 
One remark, I do not understand why we prevent the children power to be higher then the parents power. I thought this is exactly the use case we want to have. 
Example:
- Parent 100kW
- 1 Child 70kW
- 2 Child 70kW
Both children could consume140kW, smart charging will automatically take this into account and prevent blowing the parent fuse, by limiting the sub fuses.
Additionally parent limit could be increased by solar production to provide a higher limit.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Thanks for all the refinements. One remark, I do not understand why we prevent the children power to be higher than the parents power. I thought this is exactly the use case we want to have. Example:
> 
> * Parent 100kW
> * 1 Child 70kW
> * 2 Child 70kW
>   Both children could consume140kW, smart charging will automatically take this into account and prevent blowing the parent fuse, by limiting the sub fuses.
>   Additionally parent limit could be increased by solar production to provide a higher limit.

@OliveGerste Thanks for your feedback!
Indeed, if it's managed by the optimizer, then no need to check the children's power.
I'll remove the assertion.

**Comment by LucasBrazi06** [comment]
> @OliveGerste Thanks for your feedback!
> Indeed, if it's managed by the optimizer, then no need to check the children's power.
> I'll remove the assertion.

Done.

**Review by LucasBrazi06 — APPROVED** [review]

**Pull request merged**
