### PR TITLE
billing - preserve session billing data

### PR DESCRIPTION
**Pull request by ClaudeROSSI**
URGENT!

hot fix to make sure the billing data of the last transaction is preserved when computing the extra inactivity

### CODE REVIEW

**Comment by ClaudeROSSI** [comment]
@LucasBrazi06 : This one is a bit important!
I will have to also have a task to repair sessions where the billing data does not include the invoice number anymore!

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 : This one is a bit important! I will have to also have a task to repair sessions where the billing data does not include the invoice number anymore!

You need a deployment?

**Comment by ClaudeROSSI** [comment]
> > @LucasBrazi06 : This one is a bit important! I will have to also have a task to repair sessions where the billing data does not include the invoice number anymore!
> 
> You need a deployment?

a deployment would be cool ... but anyway, we already have a lot of sessions to repair ... so the deployment can wait.
This only impact the session history ... where the invoice number is not shown anymore!

**Comment by LucasBrazi06** [comment]
> a deployment would be cool ... but anyway, we already have a lot of sessions to repair ... so the deployment can wait.
> This only impact the session history ... where the invoice number is not shown anymore!

Ok, let me know then.

**Pull request merged**
