### PR TITLE
Site Authorization Concept Enhancement (use dynamic filters)

### PR DESCRIPTION
**Pull request by roxiciobotea210**
I'm not sure if anything is missing, the assign users scenario was very confusing to implement.

### CODE REVIEW

**Review by LucasBrazi06 — COMMENTED** [review]
I haven't gone through every line of code but it looks very good!
I'll test it along the front-end that needs little changes.
Let me know if you need a small task or may we can improve the unit tests?

**Comment by roxiciobotea210** [comment]
> I haven't gone through every line of code but it looks very good!
> I'll test it along the front-end that needs little changes.
> Let me know if you need a small task or may we can improve the unit tests?

Thanks a lot for checking @LucasBrazi06 ! Let me know if you find anything missing.
I was thinking to do the same changes for SiteAreas since this is just for the Sites. Is that ok?

**Comment by LucasBrazi06** [comment]
> I was thinking to do the same changes for SiteAreas since this is just for the Sites. Is that ok?

Yes go ahead.

**Comment by roxiciobotea210** [comment]
Please do not merge this yet, I found some things I can improve while working on SiteAreas, will work on it tomorrow. :)

**Comment by LucasBrazi06** [comment]
@roxiciobotea210 I tested the app and found out that the admin user cannot delete anymore any users.
Could you check?
Thanks!

**Comment by roxiciobotea210** [comment]
> @roxiciobotea210 I tested the app and found out that the admin user cannot delete anymore any users.
> Could you check?
> Thanks!

Issue should be fixed now.

**Pull request merged**
