### PR TITLE
Billing - STRIPE - feature toggle 

### PR DESCRIPTION
**Pull request by ClaudeROSSI**
Feature toggles have been introduced to make it easier to check the intermediate versions of the STRIPE implementation.

- Feature.BILLING_SYNC_USERS
- Feature.BILLING_SYNC_USER,
- Feature.BILLING_CHECK_USER_BILLING_DATA,
- Feature.BILLING_CHECK_CUSTOMER_ID,
- Feature.BILLING_CHECK_USER_DEFAULT_PAYMENT_METHOD,

The features can be switched ON/OFF depending on our needs.
The goal is to be able to only activate part of the features. This will allow to step by step validate the flow on a productive environment (i.e.: SLF PROD).

In this first integration, only selected beta-testers will have the ability to check the billing capabilities. The beta-testeurs are the ones having billing data attached to their user. This data can only be added by explicitly/manually calling a "Force Sync User".

Moreover the billing of charging sesions (transactions) is disabled with the default BILLING settings. The UI to enable it is not yet available.

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI Conflicts to solve.

**Comment by ClaudeROSSI** [comment]
conflict with jerome reordering solved

**Comment by ClaudeROSSI** [comment]
utbilling tests are failing!

**Comment by ClaudeROSSI** [comment]
billing tests should now be ok

**Pull request merged**
