### PR TITLE
Dedupe MeterValues in enum + cleanups

### PR DESCRIPTION
**Pull request by jerome-benoit**
Update: 

+ reverted to previous behaviour on the phase assignment. 

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Review by OliveGerste — COMMENTED** [review]
We have a similar check in the charging station service. Should this be updated too?

**Comment by jerome-benoit** [comment]
> We have a similar check in the charging station service. Should this be updated too?

No, customers move a charging station three-phased in the template to a one phase site area but when they configure it manually, the backend have to make sure the number of its phase math the site area.

**Comment by OliveGerste** [comment]
> > We have a similar check in the charging station service. Should this be updated too?
> 
> No, customers move a charging station three-phased in the template to a one phase site area but when they configure it manually, the backend have to make sure the number of its phase match the site area.

Okay, so we can keep it as it is.

**Comment by jerome-benoit** [comment]
> > > We have a similar check in the charging station service. Should this be updated too?
> > 
> > 
> > No, customers move a charging station three-phased in the template to a one phase site area but when they configure it manually, the backend have to make sure the number of its phase match the site area.
> 
> Okay, so we can keep it as it is.

@OliveGerste: I you approve that PR, could please flag it as it? That will ease Serge work at his return.

**Comment by LucasBrazi06** [comment]
Why does the customer can't first set up his charging station to single phase and next assign it to the site area?

**Pull request merged**
