### PR TITLE
Add new projected fields to Get User Default Tag Car endpoint

### PR DESCRIPTION
**Pull request by mahdibenromdhane**

### CODE REVIEW

**Review by AlixH — APPROVED** [review]

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Did you check the OAS file (Swagger)?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane Did you check the OAS file (Swagger)?

No, it's done now.

**Comment by LucasBrazi06** [comment]
> > @mahdibenromdhane Did you check the OAS file (Swagger)?
> 
> No, it's done now.

PR :-) ?

**Comment by mahdibenromdhane** [comment]
> > > @mahdibenromdhane Did you check the OAS file (Swagger)?
> > 
> > 
> > No, it's done now.
> 
> PR :-) ?

Done :)

**Pull request merged**
