### PR TITLE
Change TenantId to Object in CompanyStorage

### PR DESCRIPTION
**Pull request by RohanAntony**
Usage of Tenant Id within CompanyStorage was changed to using tenant object.

### CODE REVIEW

**Comment by OliveGerste** [comment]
@LucasBrazi06 I will talk with Rohan how to make changes to submodules. 
I guess the concur integration uses the company storage. This is why the build fails.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 I will talk with Rohan how to make changes to submodules.
> I guess the concur integration uses the company storage. This is why the build fails.

Yes :)

**Comment by RohanAntony** [comment]
I would like to keep only one PR per issue. I am closing this and will reopen it after the first one.

**Comment by RohanAntony** [comment]
Reopening second PR for the respective issue.

**Comment by RohanAntony** [comment]
Submodule PR: "Using tenant object instead of tenant id for storage access" in ev-sap-refund-concur

**Review by LucasBrazi06 — APPROVED** [review]
Gut

**Comment by LucasBrazi06** [comment]
@RohanAntony Unit Test failed due to the issue below which made me loose my time to find the root cause.
Do not forget to run properly all the Unit Tests before you create a PR.
Thanks!

**Comment by RohanAntony** [comment]
I apologize for the inconvenience caused. I saw a few errors in the unit test but assumed they were due to some other changes. I will avoid making such mistakes again. Really sorry for the inconvenience caused.

**Comment by LucasBrazi06** [comment]
> I apologize for the inconvenience caused. I saw a few errors in the unit test but assumed they were due to some other changes. I will avoid making such mistakes again. Really sorry for the inconvenience caused.

No problem Rohan, it happens ;-)

**Pull request merged**
