### PR TITLE
REST > ChargingStation requestOcppParams/UpdateParams/LimitPower schemas

### PR DESCRIPTION
**Pull request by Ninjeneer**

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@OliveGerste Could you check with the Swagger interface the changes of the Charging Station?
I'll move it to Dev Cross Review.
You can approve the issue if it's okay.
Thanks!

**Comment by jerome-benoit** [comment]
@Ninjeneer: do you test your API changes with ev-simulator?

**Comment by OliveGerste** [comment]
@Ninjeneer @LucasBrazi06 
I had a look at the swagger UI and the schemas regarding the parameters update. 
I found two things:
- The schema of the connector is missing the connector type. I found it in the swagger UI but not in the validation schema. 
- The ocppParamForPowerLimitation is not a boolean

**Comment by LucasBrazi06** [comment]
> @Ninjeneer @LucasBrazi06
> I had a look at the swagger UI and the schemas regarding the parameters update.
> I found two things:
> 
> * The schema of the connector is missing the connector type. I found it in the swagger UI but not in the validation schema.
> * The ocppParamForPowerLimitation is not a boolean

Thanks @OliveGerste !
@Ninjeneer Could you check?
I'll put the PR in requested changes.
Thanks!

**Comment by Ninjeneer** [comment]
> The schema of the connector is missing the connector type. I found it in the swagger UI but not in the validation schema.

Moved the connector type param into connector definition.

> The ocppParamForPowerLimitation is not a boolean

Fixed.

> @Ninjeneer: do you test your API changes with ev-simulator?
Because most the late bugs on the RESTful API could have been avoided by thoroughly testing the code changes with ev-simulator.

I have just set it up. It will be easier now, thanks.

**Comment by LucasBrazi06** [comment]
@OliveGerste Could you recheck :)

**Comment by OliveGerste** [comment]
@Ninjeneer @LucasBrazi06 
I had a look again. Looks good so far, but the property of the connector type is named just 'type' and not connectorType. This needs to be changed in order to check the property in the request.

**Comment by LucasBrazi06** [comment]
@OliveGerste You can approve this PR with your blood if you agree with the change :-)
@Ninjeneer One conflict to resolve

**Comment by Ninjeneer** [comment]
> @Ninjeneer One conflict to resolve

@LucasBrazi06 done

**Comment by LucasBrazi06** [comment]
@OliveGerste Once approved, could you put it back to To be reviewed pipeline?
Thanks

**Review by LucasBrazi06 — APPROVED** [review]

**Pull request merged**
