### PR TITLE
Endpoint to export ocpi consumption data for advenir

### PR DESCRIPTION
**Pull request by mahdibenromdhane**

### CODE REVIEW

**Comment by ClaudeROSSI** [comment]
@mahdibenromdhane : I did some fixes 
- the consumption values where in a random order (missing field in the projection)
- the timestamp was a string (instead of a number)
- the timestamp was not the one ADVENIR expects

I also changed the ADVENIR types to makevahe a strong-typed payload

Please try it again on your side and let me know what you think

**Comment by ClaudeROSSI** [comment]
@mahdibenromdhane : It would be convenient to pass the userID has a query parameter to have it already populated in the response. What do you think?

image

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane : I did some fixes
> 
> * the consumption values where in a random order (missing field in the projection)
> * the timestamp was a string (instead of a number)
> * the timestamp was not the one ADVENIR expects
> 
> I also changed the ADVENIR types to makevahe a strong-typed payload
> 
> Please try it again on your side and let me know what you think

It works good thanks :)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane : It would be convenient to pass the userID has a query parameter to have it already populated in the response. What do you think?
> 
> image

Good Idea, I did the necessary changes.

**Review by ClaudeROSSI — APPROVED** [review]

**Pull request merged**
