### PR TITLE
Additional statistics aggregation options

### PR DESCRIPTION
**Pull request by changesbyjames**
Hey 👋!
As part of our work with EZ-Charge and building their analytics dashboard we've needed some more aggregation options for the statistics endpoints.

We've kept it simple for this initial implementation so we have:
* Added validation for incoming requests to include additional data scopes.
* Applied the month scope as the default, to ensure backward compatibility.
* Ensured those aggregations queries are formatted properly for MongoDB.
* Made the graph data formatter generic to any period, while ensuring backwards compatibility.

Future changes could include:
- [ ] Extending these scopes to the export API.
- [ ] Exposing these aggregation options in the statistics view in the ev-dashboard.

Looking forward to your feedback, thanks!

### CODE REVIEW

**Comment by changesbyjames** [comment]
Hey, I hope all is good. Is there anything I can do to help make this green? I believe that the submodule related checks are reliant on a private repo I don't have access to but is the lint failure something I can help with?

Thanks, James.

**Comment by changesbyjames** [comment]
Hey, I just wanted to check in and see if there's anything I can do to help make this green? Let me know!
Thanks, James

**Comment by ClaudeROSSI** [comment]
> Hey, I just wanted to check in and see if there's anything I can do to help make this green? Let me know! Thanks, James

Sorry for the late reply.
We are moving to Kubernetes and this will impact our CI/CD. Our goal is to get rid of the private sub-modules but this will take time. 

I'll try to merge your change even though the automated tests are not running.

**Comment by ClaudeROSSI** [comment]
@Ramzay : do you see any risks in that PR?

**Comment by Ramzay** [comment]
Hey @changesbyjames,

Sorry for the late reply ! And unfortunately I bring you some bad news... There is an issue when we call the export statistics endpoint with **DataScope=total**

Here is an example to reproduce:
_/v1/api/statistics/action/export?StartDateTime=2021-12-31T23:00:00.000Z&EndDateTime=2022-09-30T21:59:59.999Z&Year=2022&DataType=Consumption&DataCategory=C&DataScope=total_

This is a valid datascope and is expected to be used when calling our API :) 
Could you please have a look ?

Cheers, Ramzi

**Review by Ramzay — CHANGES_REQUESTED** [review]
Please check my above comment

**Review by Ramzay — APPROVED** [review]
All good !

@ClaudeROSSI we can merge this one

**Pull request merged**
