### PR TITLE
Final Auth concept without roles for Company

### PR DESCRIPTION
**Pull request by LucasBrazi06**

### CODE REVIEW

**Review by roxiciobotea210 — APPROVED** [review]
Code is definitely more complex now, but it looks much cleaner! 
All seems to be working well & I understand the general concept. I will definitely understand it better when implementing Sites & the rest of entities. :)

**Comment by LucasBrazi06** [comment]
> Code is definitely more complex now, but it looks much cleaner!
> All seems to be working well & I understand the general concept. I will definitely understand it better when implementing Sites & the rest of entities. :)

Okay, thanks for your feedback!

**Comment by roxiciobotea210** [comment]
@LucasBrazi06 So should I start on Sites? :)

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 So should I start on Sites? :)

Yes :-)
Let me know if you need any help!

**Pull request merged**
